#ifndef PROTOCOL_H
#define PROTOCOL_H

typedef unsigned int uint;

enum ENUM_MSG_TYPE {//消息类型的枚举值
    ENUM_MSG_TYPE_MIN=0,
    ENUM_MSG_TYPE_REGIST_REQUEST,
    ENUM_MSG_TYPE_REGIST_RESPOND,
    ENUM_MSG_TYPE_LOGIN_REQUEST,
    ENUM_MSG_TYPE_LOGIN_RESPOND,
    ENUM_MSG_TYPE_FIND_USER_REQUEST,
    ENUM_MSG_TYPE_FIND_USER_RESPOND,
    ENUM_MSG_TYPE_ONLINE_USER_REQUEST,
    ENUM_MSG_TYPE_ONLINE_USER_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_AGREE_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_AGREE_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FRIEND_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FRIEND_RESPOND,
    ENUM_MSG_TYPE_CHAT_REQUEST,
    ENUM_MSG_TYPE_CHAT_RESPOND,
    ENUM_MSG_TYPE_MKDIR_REQUEST,
    ENUM_MSG_TYPE_MKDIR_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FILE_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FILE_RESPOND,
    ENUM_MSG_TYPE_DEL_FILE_REQUEST,
    ENUM_MSG_TYPE_DEL_FILE_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_INIT_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_INIT_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_AGREE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_AGREE_RESPOND,
    ENUM_MSG_TYPE_MAX=99999,
};


struct PDU { //协议数据单元
    uint uiTotalLen;    //总长度
    uint uiMsgLen;      //柔性数组长度（消息长度）
    uint uiType;        //类型
    char caData[64];    //参数，数据长度小于参数长度就放到参数里
    char caMsg[];       //消息
};

struct FileInfo {
    char caName[32];
    uint uiType;
};

PDU* mkPDU(uint uiMsgLen=0);



#endif // PROTOCOL_H
